### ISSUE TITLE
Project verify does not write project aliases file.

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#270]
Only site verify actually saves the ~/.drush/project_aliases/*.aliases.drushrc.php file.

**Comment by caldenjacobs** [comment]
As far as I can tell, this totally blocks successfully verifying a platform in order to even create a site. 

All project verify tasks are resulting in "(returned:  [preflight] The alias @platform_sitename_dev could not be found., code: 0)" errors on a fresh 1.3.4 install.

**Comment by caldenjacobs** [comment]
The sitename.aliases.drushrc.php files are being created, but they're empty aside from the placeholder text, "<?php // Automatically written by devshop. Do Not Edit."

**Comment by jonpugh** [comment]
I believe I fixed this in 1.x. 

@caldenjacobs can you try upgrading to 1.x?

**Comment by jonpugh** [comment]
Just to be clear: those aliases are a bonus, not required. All work is actually done on the platform and site aliases.

If your project does not have successfully added platforms or sites, the project aliases will be empty, because there are no active environments.

**Comment by caldenjacobs** [comment]
Thanks for the reply @jonpugh 

I went ahead and did a fresh install with 1.x. Every platform verify is still presenting the error, "(returned: [preflight] The alias @platform_sitename_dev could not be found., code: 0)", so I'm unable to finish platform or project creation. 

The logs are indicating that the git pull and composer installation went well.

**Comment by jonpugh** [comment]
Can you possibly show what your repo structure looks like? 

Did you fill in "Path to Drupal" correctly? If you are using drupal-conposer-project-template, you need to use "web".

Given the git pull and composer install worked I think it's probably that.

If your platform is already created but not successfully verified, you can Edit it to fix the "publish path" to add "web" manually.

**Comment by caldenjacobs** [comment]
The composer.lock as well as the site live in "docroot", and that's filled in as the "Path to Drupal". Still no luck

**Comment by caldenjacobs** [comment]
I'll set up a vanilla install repo with the drupal-composer/drupal-project and give that a go. It could by my repo structure, but it seems odd that the only error I'm seeing is about aliases

**Comment by jonpugh** [comment]
Can you send a screenshot of the platform node page? Just so I can confirm
metadata there?

**Comment by caldenjacobs** [comment]
This issue was resolved for me by doing a fresh Devshop 1.x install, and then using a repo with Drush 8 required in the composer.lock, instead of Drush 9. It appears that requiring Drush 9 really takes a toll on Aegir and Devshop installations.

**Comment by jonpugh** [comment]
Actually we just solved this problem, but it's not made it's way into code yet: https://www.drupal.org/project/provision/issues/2953349#comment-12654065

If you set that environment variable it will verify a platform with drush 9.

**Comment by jonpugh** [comment]
This issue got way off topic, and I think it's fixed so...
