### ISSUE TITLE
supervisor job not installed during install.sh

### ISSUE THREAD

**Issue by aaronbauman** [opendevshop/devshop#67]
After install, none of my tasks were being processed.
I restarted supervisor, but to no avail because /etc/supervisor/conf.d/ was empty

Installed from install.sh, latest

 OS: ubuntu
 Version: 14.04
Checking for DevShop CLI...  DevShop CLI is installed.  0.x dafb71d
Checking for Drush...  Drush is installed.  Drush Version   :  6.7.0
Checking for Provision...  Provision is installed.
Checking for DevMaster...  Devmaster is installed.  0.x

**Comment by jonpugh** [comment]
Ahhh thanks.

I fixed this in 1.x and forgot to backport it.

Please pull the latest install.sh and try again!

Thanks,
Jon

**Comment by aaronbauman** [comment]
in the meantime i copied the conf manually, but it's still getting skipped while running install.sh:
```
TASK: [Supervisor | Set up queue runner script] ******************************* 
skipping: [xxx]

TASK: [Supervisor | Set up supervisor job] ************************************ 
skipping: [xxx]

TASK: [Service | Ensure Supervisor is restarted] ****************************** 
skipping: [xxx]
```

**Comment by jonpugh** [comment]
The default is in `vars.yml` which is set to true...

It is overridden in install.sh here: https://github.com/opendevshop/devshop/blob/0.x/install.sh#L257

Can you make sure that line is correct?  I just changed it in https://github.com/opendevshop/devshop/commit/8e1f6489e7c4ed4ed31e69614fcf264ed00ae0a5

**Comment by jonpugh** [comment]
Thanks a ton for pointing this out, @aaronbauman. 

We will put out a point release tomorrow.  The fix is in playbook.yml.  If you update your CLI by running `git pull` in /usr/share/devshop, you will get the latest playbook.

then just run `bash /usr/share/devshop/install.sh` and it should setup your supervisor jobs.

Let me know how it goes!
Jon
